name: Node.js CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: |
        npm install
        npm install --save-dev eslint
        
    - name: Run linting
      run: npx eslint src/
      
    - name: Run tests
      run: npm run test:nowatch
      env:
        CI: true
        
    - name: Build
      run: npm run build 