name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: group-travel-app-ui/package.json
        
    - name: Install dependencies
      run: |
        cd group-travel-app-ui
        npm install
        npm install --save-dev eslint
        
    - name: Run linting
      run: |
        cd group-travel-app-ui
        npx eslint src/
      
    - name: Run tests
      run: |
        cd group-travel-app-ui
        npm test
      env:
        CI: true
        
    - name: Build
      run: |
        cd group-travel-app-ui
        npm run build 